"""The secure CBAS scheme of Qiao et al. (IEEE Systems Journal 17(1), 2023).

Reference implementation: a direct transliteration of Section V-A, with names
matching the paper so that it can be diffed against the text.  Optimisation
(multi-scalar multiplication, fixed-base tables) belongs in a separate module
so that this one stays auditable.

The three changes this scheme makes to Verma et al.'s broken CB-CAS, and what
each buys, are marked ``Fix #1/#2/#3`` at their site below.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from .backend.base import Backend
from .hashing import H0, H1, H2


# --------------------------------------------------------------------------
# Data model
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class PublicParams:
    """``Params = (G, p, P, H0, H1, H2, P_TA, D)``."""

    backend: Backend
    pk_ta: object          # P_TA = s*P
    delta: bytes = b""     # D, the public state information

    @property
    def be(self) -> Backend:
        return self.backend


@dataclass(frozen=True)
class MasterSecretKey:
    """``sk_TA = s``.  Held by the KGC; the adversary F2 is assumed to have it."""

    s: object


@dataclass(frozen=True)
class UserKeyPair:
    """``(pk_i, sk_i) = (s_i * P, s_i)``.  Generated by the sensor itself."""

    sk: object
    pk: object


@dataclass(frozen=True)
class Certificate:
    """``Cert_i = (c_i, R_i)``.  ``R_i`` is public and treated as part of the key."""

    c: object
    R: object


@dataclass(frozen=True)
class Signer:
    """The public data a verifier needs: identity, public key, and ``R_i``."""

    identity: bytes
    pk: object
    R: object


@dataclass(frozen=True)
class Signature:
    """``delta_i = (T_i, z_i)``."""

    T: object
    z: object


@dataclass(frozen=True)
class AggregateSignature:
    """``delta = (T, z)`` where ``T = (T_1, ..., T_n)`` and ``z = sum z_i``.

    Note that ``T`` cannot be compressed: each ``T_i`` is needed to recompute
    that signer's ``v_i`` and ``u_i``.  Only the scalar half aggregates, giving
    ``n|G| + 1|Z_q*|``.  Verma et al.'s constant-size aggregate was achieved by
    dropping ``R_i`` from the hash -- which is exactly what broke their scheme.
    """

    T: tuple
    z: object

    @property
    def n(self) -> int:
        return len(self.T)


# --------------------------------------------------------------------------
# (1) Setup
# --------------------------------------------------------------------------

def setup(backend: Backend, delta: bytes = b"epoch-0") -> tuple[PublicParams, MasterSecretKey]:
    """``(Params, sk_TA) <- Setup(1^k)``.  Run by the KGC."""
    s = backend.scalar_random()
    pk_ta = backend.point_mul_base(s)
    return PublicParams(backend=backend, pk_ta=pk_ta, delta=delta), MasterSecretKey(s=s)


# --------------------------------------------------------------------------
# (2) KeyGen
# --------------------------------------------------------------------------

def keygen(params: PublicParams) -> UserKeyPair:
    """``(pk_i, sk_i) <- KeyGen(1^k)``.  Run by the sensor; the KGC never sees sk_i."""
    be = params.be
    sk = be.scalar_random()
    return UserKeyPair(sk=sk, pk=be.point_mul_base(sk))


# --------------------------------------------------------------------------
# (3) CertGen
# --------------------------------------------------------------------------

def cert_gen(params: PublicParams, msk: MasterSecretKey, identity: bytes, pk) -> Certificate:
    """``Cert_i <- CertGen(id_i, pk_i, sk_TA)``.  Run by the KGC.

    Fix #1: ``R_i`` is hashed into ``H0`` alongside the identity and public key,
    so a public-key replacement cannot detach the certificate from the key.
    """
    be = params.be
    r = be.scalar_random()
    R = be.point_mul_base(r)
    h0 = H0(be, identity, pk, R)                       # Fix #1: R inside H0
    c = be.scalar_add(r, be.scalar_mul(msk.s, h0))     # c_i = r_i + s*H0(id||pk||R)
    return Certificate(c=c, R=R)


def cert_verify(params: PublicParams, identity: bytes, pk, cert: Certificate) -> bool:
    """Check ``c_i * P == R_i + H0(id||pk||R) * P_TA``."""
    be = params.be
    lhs = be.point_mul_base(cert.c)
    h0 = H0(be, identity, pk, cert.R)
    rhs = be.point_add(cert.R, be.point_mul(h0, params.pk_ta))
    return be.point_eq(lhs, rhs)


# --------------------------------------------------------------------------
# (4) Sign
# --------------------------------------------------------------------------

def sign(params: PublicParams, signer: Signer, sk, cert: Certificate, message: bytes) -> Signature:
    """``delta_i <- Sign(id_i, sk_i, Cert_i, pk_i, m_i)``.  Run by the sensor.

    Fix #2: the nonce commitment ``T_i`` is hashed into *both* ``H1`` and ``H2``.
    This is what defeats the malicious-KGC forgery against Verma et al.: an
    attacker can no longer compute the coefficient for a new message without
    first fixing ``T_i``, and changing ``T_i`` changes the coefficient again.

    Fix #3: the certificate term is scaled by ``u`` and the secret-key term by
    ``v`` -- two *independent* random-oracle coefficients.  See ``hashing.py``.
    """
    be = params.be
    t = be.scalar_random()
    T = be.point_mul_base(t)                                          # 1 Te
    v = H1(be, message, signer.pk, signer.R, signer.identity, T, params.delta)
    u = H2(be, message, signer.pk, signer.R, signer.identity, T, params.delta)
    # z_i = t_i + c_i * u_i + sk_i * v_i
    z = be.scalar_add(t, be.scalar_add(be.scalar_mul(cert.c, u), be.scalar_mul(sk, v)))
    return Signature(T=T, z=z)


# --------------------------------------------------------------------------
# (5) AggSign
# --------------------------------------------------------------------------

def agg_sign(params: PublicParams, signatures: Sequence[Signature]) -> AggregateSignature:
    """``delta <- AggSign(delta_1, ..., delta_n)``.  Run by the aggregator.

    Uses no secret material -- which is why the security of the aggregate
    scheme reduces to that of the single-signer scheme.

    Cost note: this performs ``n-1`` *scalar* additions in Z_p and zero group
    operations.  Table III charges it ``(n-1)Ta``, i.e. group additions.  For
    Verma et al. that is correct (they also compute ``R = sum R_i`` in the
    group); for this scheme it overstates the cost.
    """
    be = params.be
    if not signatures:
        raise ValueError("cannot aggregate an empty signature list")
    z = be.sum_scalars([s.z for s in signatures])
    return AggregateSignature(T=tuple(s.T for s in signatures), z=z)


# --------------------------------------------------------------------------
# (6) AggVerify
# --------------------------------------------------------------------------

def agg_verify(
    params: PublicParams,
    signers: Sequence[Signer],
    messages: Sequence[bytes],
    aggsig: AggregateSignature,
) -> bool:
    """``1/0 <- Very(delta, m_1, ..., m_n)``.  Run by the cloud server.

    Checks::

        z*P == sum(T_i) + sum(u_i * R_i) + (sum u_i*h_i0) * P_TA + sum(v_i * pk_i)

    Written as the paper writes it, one term at a time.  The operation counts
    this produces are the subject of the Table III experiment.
    """
    be = params.be
    n = len(signers)
    if not (n == len(messages) == len(aggsig.T)):
        raise ValueError(
            f"length mismatch: {n} signers, {len(messages)} messages, {len(aggsig.T)} commitments"
        )
    if n == 0:
        raise ValueError("cannot verify an empty aggregate")

    lhs = be.point_mul_base(aggsig.z)                                  # 1 Te

    uR_terms = []
    vpk_terms = []
    uh_acc = None
    for signer, message, T in zip(signers, messages, aggsig.T):
        h0 = H0(be, signer.identity, signer.pk, signer.R)              # Th
        v = H1(be, message, signer.pk, signer.R, signer.identity, T, params.delta)   # Th
        u = H2(be, message, signer.pk, signer.R, signer.identity, T, params.delta)   # Th
        uR_terms.append(be.point_mul(u, signer.R))                     # Te  <- absent from Verma
        vpk_terms.append(be.point_mul(v, signer.pk))                   # Te
        uh = be.scalar_mul(u, h0)
        uh_acc = uh if uh_acc is None else be.scalar_add(uh_acc, uh)

    sum_T = be.sum_points(aggsig.T)                                    # n-1 Ta
    sum_uR = be.sum_points(uR_terms)                                   # n-1 Ta
    sum_vpk = be.sum_points(vpk_terms)                                 # n-1 Ta
    term_ta = be.point_mul(uh_acc, params.pk_ta)                       # 1 Te

    rhs = be.point_add(sum_T, sum_uR)                                  # Ta
    rhs = be.point_add(rhs, term_ta)                                   # Ta
    rhs = be.point_add(rhs, sum_vpk)                                   # Ta

    return be.point_eq(lhs, rhs)


def verify_single(params: PublicParams, signer: Signer, message: bytes, sig: Signature) -> bool:
    """Verify one signature.

    Needed in its own right for aggregator-side pre-verification, which
    mitigates the all-or-nothing failure mode of aggregate verification: once
    signatures are summed, a single bad ``z_i`` invalidates the whole batch and
    the individual ``z_i`` are gone, so the culprit cannot be identified.
    """
    return agg_verify(
        params,
        [signer],
        [message],
        AggregateSignature(T=(sig.T,), z=sig.z),
    )
